### PR TITLE
feature: support for M1 macOS & asdf-nim

### PR DESCRIPTION
**Pull request by elijahr**
- Prevent nimble script from trying and failing to run jupyternim in after-install hook on macOS M1.  M1 Homebrew lives in /opt/homebrew so libzmq.dylib is in a non-standard location and isn't found by default. Setting DYLD_LIBRARY_PATH works in some cases, but macOS has a security feature called "SIP" which nulls out DYLD_LIBRARY_PATH for some child procs (/bin/sh, /usr/bin/env). gorgeEx uses /bin/sh, so running jupyternym from NimScript will fail to find libzmq.dylib. The workaround is to simply tell the user to run `jupyternim` manually. 
- Support for [asdf-nim](https://github.com/asdf-community/asdf-nim); the output of `nimble path jupyternim` will be two lines instead of one so `[^1]` is used instead of `[0]`.
- Upgrade to zmq-nim ~=1.2.1. Pin other dependencies.
- Place correct version of Nim in kernel's `language_info.version` field. The compiler version of nim and the version of nim being used by the kernel could be different.

### CODE REVIEW

**Comment by stisa** [comment]
Hey! Thanks very much for the PR, I am little busy but I'll have a better look and merge it on the weekend.  
I saw you added a dependency on regex to parse nim version, which I think could be done by just taking the first line of the response of `nim -v` and cutting off the beginning. I'd prefer not adding a dependency just for this, what do you think?

**Comment by elijahr** [comment]
> Hey! Thanks very much for the PR, I am little busy but I'll have a better look and merge it on the weekend. I saw you added a dependency on regex to parse nim version, which I think could be done by just taking the first line of the response of `nim -v` and cutting off the beginning. I'd prefer not adding a dependency just for this, what do you think?

Yeah, I think we can make it work without the additional dependency. I'll assign this to myself and assign to you when it's ready. Thanks!

**Comment by elijahr** [comment]
@stisa I've removed the regex dependency, it's ready for review.

**Comment by stisa** [comment]
LGTM, thanks!

**Pull request merged**
